#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: JS Tips

# Short bio or description (displayed in the header)
description: A JS tip per day!

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: http://www.jstips.co/images/jstips.png

url: http://jstips.co

#
# Flags below are optional
#
defaults:
  -
    scope:
      path: _posts/en
      type: posts
    values:
      layout: default
      lang: en
      is_post: true
  -
    scope:
      path: _posts/zh_CN
      type: posts
    values:
      layout: default
      lang: zh_CN
      is_post: true
  -
    scope:
      path: _posts/zh_TW
      type: posts
    values:
      layout: default
      lang: zh_TW
      is_post: true

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: tipsjs

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-72764095-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:categories/:title/

paginate: 10
paginate_path: "/:num/"

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  # - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME

# languages var
languages:
  -
    name: en
    link: /
  -
    name: zh_CN
    link: /zh_CN
  -
    name: zh_TW
    link: /zh_TW

transl:
  en:
    menu:
      home:
        txt: Home
        link: /
      about:
        txt: About
        link: /about
      subscribe:
        txt: Subscribe
      submit_your_tip:
        txt: Submit your tip
        link: https://github.com/loverajoel/jstips/blob/gh-pages/CONTRIBUTING.md
    footer_subscribe_message: Subscribe to more awesome daily tips!
    footer_placeholder_subscribe: your@email.com
    arrow_prev: Previous Tip
    arrow_next: Next Tip
  zh_CN:
    menu:
      home:
        txt: 主页
        link: /zh_CN
      about:
        txt: 关于
        link: /zh_CN/about
      subscribe:
        txt: 订阅
      submit_your_tip:
        txt: 提交小知识
        link: https://github.com/loverajoel/jstips/blob/gh-pages/CONTRIBUTING_zh_CN.md
    footer_subscribe_message: 订阅，每天获取一条小知识!
    footer_placeholder_subscribe: your@email.com
    arrow_prev: 上一条
    arrow_next: 下一条
  zh_TW:
    menu:
      home:
        txt: 首頁
        link: /
      about:
        txt: 關於
        link: /about
      subscribe:
        txt: 訂閱
      submit_your_tip:
        txt: 提交你的小知識
        link: https://github.com/loverajoel/jstips/blob/gh-pages/CONTRIBUTING_zh_TW.md
    footer_subscribe_message: 訂閱更多更棒的每日小知識！
    footer_placeholder_subscribe: your@email.com
    arrow_prev: 上一篇小知識
    arrow_next: 下一篇小知識
